---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicaldynamicsecrets
  - infisicalpushsecretsecrets
  - infisicalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicaldynamicsecrets/finalizers
  - infisicalpushsecretsecrets/finalizers
  - infisicalsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicaldynamicsecrets/status
  - infisicalpushsecretsecrets/status
  - infisicalsecrets/status
  verbs:
  - get
  - patch
  - update
