apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
    name: infisicalsecret-sample
    labels:
        label-to-be-passed-to-managed-secret: sample-value
    annotations:
        example.com/annotation-to-be-passed-to-managed-secret: "sample-value"
spec:
    hostAPI: http://localhost:8085/api
    resyncInterval: 10
    authentication:
        # Native Kubernetes Auth
        kubernetesAuth:
            identityId: 25d05878-0a2f-47c5-b889-46b70fb2dbfc
            serviceAccountRef:
              name: infisical-auth
              namespace: default

            # secretsScope is identical to the secrets scope in the universalAuth field in this sample.
            secretsScope:
                projectSlug: test-j7-kx
                envSlug: dev
                secretsPath: "/"
                recursive: true


    managedSecretReference:
        secretName: managed-secret-k8s
        secretNamespace: default
        creationPolicy: "Orphan" ## Owner | Orphan
        # secretType: kubernetes.io/dockerconfigjson
